APPIUM_ADDRESS = "http://localhost:4723/wd/hub"
APP_PACKAGE = "br.westwing.android"
APP_ACTIVITY = ".presentation.activities.SplashActivity"
PLATFORM_NAME = "Android"
NORESET = "noReset"
SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/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"
