lateralMenu = '//android.widget.ImageButton[@content-desc="Navigate up"]'
accountInformationButton = 'br.westwing.android:id/nav_account_settings'
cpfTextField = '//android.widget.EditText[@resource-id="AccountEditForm_tax_identification"]'
userNameTextField = '//android.widget.EditText[@resource-id="AccountEditForm_first_name"]'
userLastNameTextField = '//android.widget.EditText[@resource-id="AccountEditForm_last_name"]'
genderSpinner = '//android.widget.Spinner[@resource-id="AccountEditForm_gender"]'
birthDateDay = '//android.widget.Spinner[@resource-id="AccountEditForm_day"]'
birthDateMonth = '//android.widget.Spinner[@resource-id="AccountEditForm_month"]'
birthDateYear = '//android.widget.Spinner[@resource-id="AccountEditForm_year"]'
userEmailTextField = '//android.widget.EditText[@resource-id="AccountEditForm_email"]'
saveModificationsButton = '//android.widget.Button[@resource-id="wwqa-myAccountSubmit"]'
changePasswordButton = '//android.view.View[resource-id="wwqa-myAccountChangePassLink"]/android.widget.TextView'
oldPassTextField = '//android.widget.EditText[@resource-id="id0"]'
newPassTextField = '//android.widget.EditText[@resource-id="id1"]'
